pipeline {
    agent {
        docker {
            image 'node:18-alpine'
        }
    }
    stages {
        stage('Install') {
            steps {
                sh 'npm ci'
            }
        }

   

        stage('Deploy') {
    steps {
        sh '''
            docker build -t my-react-app .
            docker run -d -p 3001:3000 my-react-app
        '''
    }
}
    }
}
