pipeline {
    agent any

    stages {
        stage('Withdocker') {
            steps {
                agent{
                    docker{
                        image 'node:latest'
                        args '-p 3000:3000'
                        name 'my-node-app'
                        reuseNode true
                    }
                }

                echo 'Hello World2'
                Sh'''
                ls -la
                npm -version
                node -version
                ls -la
                '''
            }
        }
    }
}